version: '3'

services:
  sleek-airflow:
    image: task3-airflowtask3:latest
    build:
    
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./airflow:/opt/airflow
    ports:
      - "8080:8080"
    command: airflow standalone
